apiVersion: v1
binaryData:
  default-local.tar.gz: H4sIAM4wWGMAA+1V227aQBDlma/wF+Ar8FD1AZmkikJTK6ZS39Bij8M2611rd02Fqvx792IbqCAVSWjVlpHQmPHMmcuZXQ/c3tnF87zxcOgYPbLaCyKrG3H8KAhDL/LDKHQ8P/TCqOcMz19ar1cLibgqpeKIfkWkQhKTQ37KrSiewWn66PRfIgOX1BQtMkYL/HCmXTid/2EYeBf+f4fs8x+v+EZI9ogH2vBWOdQ8Rs1oDvEfjKKf+A88P1L8e29VwHPyn/PfMR44753vfcdxZnj5+e7mi/rrskq6eFm6OZKoYt+Au7XgrkAFUJBmcTKCgapHvNS/mG8qgzUQ7N0O1ih6FdpiFBnAp35/pryaQqdQoJrIOS7hUy2VcWgmr/MmV1NtZrX0ld3v7DsvdLvBgYCwtWvzLWwqhPkHoNsswbiLigmjmD7ErCwRzbcu4dZj71UCeQraYdxkUA3FiOf3gHLgTVv3UDIJTaCu3rh9xCJrHJIrfxyNrihaEtAOtrM5Y0RMMT9p0EtM7VgQl1hiRhNGcLaZQ1kRJCFBcnUYL+dqVEoTliGyd4NoH7dq8RaVAVzIBlHYdFx1mEnIJ7VcqTpwhkxyle6aoIdUIlkL29mTYTydqFnritsdvYcM8BoaznYpc9J0FptSrjGBU6ehnIEKQQYZLQyaTZtwvFa7cByxnYeArOagE2TApXB3MGJleCFACnwNPJ6cHm6ZUY+ujR5UUBrIO5DdRH27QHFyC1BNiJpru3apgXPmXF2SatfiFaIUSEuCBZizR6DqnL/khKessPHtfdEZjm7y8c2zaqr3T2qIndnf5HrLJIbjJ+QXG23rXuAOaP/cvD7B9sjs5njq/+nvw0UucpF/V34ABBULXAAQAAA=
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: default-local
-e   annotations: 
    argocd.argoproj.io/sync-wave: "335"
