<?xml version="1.0" encoding="utf-8"?>

<!--
  Copyright (c) 2006 IBM, Inc.
  All Rights Reserved.
-->

<wsdl:definitions name="soaplog"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd='http://www.w3.org/2001/XMLSchema'
  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:wsdlsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
  xmlns:wsdltns="http://www.ibm.com/AC/commonbaseevent1_0_1/wsdl"
  xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"
  xmlns:tns="http://www.ibm.com/AC/commonbaseevent1_0_1"
  targetNamespace="http://www.ibm.com/AC/commonbaseevent1_0_1/wsdl">

  <wsdl:types>
      <xsd:schema>
          <xsd:include schemaLocation="log-cbe.xsd"/>
       </xsd:schema>
  </wsdl:types>

  <wsdl:message name="request">
      <wsdl:part name="body" element="tns:CommonBaseEvent"/>
  </wsdl:message>

  <wsdl:message name="response">
      <wsdl:part name="body" element="response"/>
  </wsdl:message>

  <wsdl:portType name="cbelog">
      <wsdl:operation name="operation">
          <wsdl:input message="wsdltns:request"/>
          <wsdl:output message="wsdltns:response"/>
      </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="soaplog" type="wsdltns:cbelog">
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="operation">
          <wsdlsoap:operation style="document"/>
          <wsdl:input>
              <wsdlsoap:body use="literal"/>
          </wsdl:input>
          <wsdl:output>
              <wsdlsoap:body use="literal"/>
          </wsdl:output>
      </wsdl:operation>
  </wsdl:binding>

  <wsdl:binding name="soaplog12" type="wsdltns:cbelog">
      <wsdlsoap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="operation">
          <wsdlsoap12:operation style="document"/>
          <wsdl:input>
              <wsdlsoap12:body use="literal"/>
          </wsdl:input>
          <wsdl:output>
              <wsdlsoap12:body use="literal"/>
          </wsdl:output>
      </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="cbelog">
      <wsdl:port name="cbelog" binding="wsdltns:cbelog">
          <wsdl:documentation>
              <wsi:Claim conformsTo="http://ws-i.org/profiles/basic/1.0"/>
          </wsdl:documentation>
          <wsdlsoap:address location="file:///dev/null"/>
       </wsdl:port>
  </wsdl:service>

  <wsdl:service name="cbelog12">
      <wsdl:port name="cbelog12" binding="wsdltns:cbelog12">
          <wsdl:documentation>
              <wsi:Claim conformsTo="http://ws-i.org/profiles/basic/1.0"/>
          </wsdl:documentation>
          <wsdlsoap12:address location="file:///dev/null"/>
       </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
